# Generated by Django 5.0.2 on 2024-06-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitkha_app', '0006_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='user',
        ),
    ]
