# Generated by Django 5.0.2 on 2024-06-29 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitkha_app', '0008_rename_offer_rate_offer_percentage_offer_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='end_date',
            new_name='validity',
        ),
    ]
