# Generated by Django 5.0.2 on 2024-07-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitkha_app', '0009_rename_end_date_offer_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
