# Generated by Django 5.0.2 on 2024-07-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitkha_app', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='table_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
